### ISSUE TITLE
nk-compare-configs specifying the baseline

### ISSUE THREAD

**Issue by itchykun** [networklore/nelkit#9]
Hi,

Referring to https://networklore.com/network-config-audit/ I was hoping to be able to specify the baseline configuration file in the tool but I can't find the option.
I place a file called 00_template (then renamed to aa_template) in my config folder but it's not the tool just ignore it and takes another configuration file as the template (and I don't know which one)

Thanks

**Comment by ogenstad** [comment]
I've released version 0.0.5 which allows you to set `baseline` in the config file, look at the updated https://networklore.com/nk-compare-configs/ for a reference.
